// data.js - list of games

const games = [
  { id: 1, name: "Cyberpunk 2077", category: "RPG", price: 29.99, original: 59.99, sale: true, rating: 4, img: "logo/cyber punk.jpg" },
  { id: 2, name: "Elden Ring", category: "RPG", price: 49.99, original: 59.99, sale: false, rating: 5, img: "logo/EldenRing.jpg" },
  { id: 3, name: "FIFA 23", category: "Sports", price: 39.99, original: 49.99, sale: true, rating: 4, img: "logo/EA SPORTS Unveils FIFA 23 Cover Athletes Kylian___.jpg" },
  { id: 4, name: "Call of Duty: Modern Warfare", category: "FPS", price: 34.99, original: 59.99, sale: true, rating: 5, img: "logo/cod_mw.jpg" },
  { id: 5, name: "Assassin's Creed Valhalla", category: "Adventure", price: 44.99, original: 59.99, sale: false, rating: 4, img: "logo/Assassin's Creed Valhalla.jpg" },
  { id: 6, name: "God of War", category: "Action", price: 29.99, original: 39.99, sale: true, rating: 5, img: "logo/God of War (2018).jpg" },
  { id: 7, name: "Horizon Forbidden West", category: "Adventure", price: 49.99, original: 59.99, sale: false, rating: 5, img: "logo/HORIZON FORBIDDEN WEST + DLC.jpg" },
  { id: 8, name: "Minecraft", category: "Sandbox", price: 19.99, original: 29.99, sale: false, rating: 5, img: "logo/mine craft.jpg" },
  { id: 9, name: "Fortnite", category: "Battle Royale", price: 0, original: 0, sale: false, rating: 4, img: "logo/fortnit.jpg" },
  { id: 10, name: "Valorant", category: "FPS", price: 0, original: 0, sale: false, rating: 4, img: "logo/valorant.jpg" },
  { id: 11, name: "League of Legends", category: "MOBA", price: 0, original: 0, sale: false, rating: 5, img: "logo/League of Legends.jpg" },
  { id: 12, name: "Dota 2", category: "MOBA", price: 0, original: 0, sale: false, rating: 5, img: "logo/dota 2.jpg" },
  { id: 13, name: "Overwatch 2", category: "FPS", price: 29.99, original: 39.99, sale: true, rating: 4, img: "logo/overwatch2.jpg" },
  { id: 14, name: "GTA V", category: "Open World", price: 19.99, original: 29.99, sale: true, rating: 5, img: "logo/gta v.jpg" },
  { id: 15, name: "Red Dead Redemption 2", category: "Open World", price: 39.99, original: 59.99, sale: false, rating: 5, img: "logo/red dead redemption 2.jpg" },
  { id: 16, name: "The Witcher 3", category: "RPG", price: 24.99, original: 39.99, sale: true, rating: 5, img: "logo/the witcher.jpg" },
  { id: 17, name: "Resident Evil Village", category: "Horror", price: 29.99, original: 59.99, sale: true, rating: 4, img: "logo/Resident evil 8 game cover.jpg" },
  { id: 18, name: "Hades", category: "Roguelike", price: 19.99, original: 24.99, sale: false, rating: 5, img: "logo/Hadès sur switch.jpg" },
  { id: 19, name: "Among Us", category: "Party", price: 4.99, original: 9.99, sale: true, rating: 4, img: "amongus.png" },
  { id: 20, name: "Dead by Daylight", category: "Horror", price: 19.99, original: 29.99, sale: true, rating: 4, img: "logo/Passe_Skin Dead by Daylight (Pix 40,00).jpg" },
  { id: 21, name: "CyberConnect 2 – Naruto Game", category: "Anime", price: 39.99, original: 59.99, sale: false, rating: 4, img: "logo/naruto.jpg" },
  { id: 22, name: "Dragon Ball Z: Kakarot", category: "Anime", price: 29.99, original: 49.99, sale: true, rating: 4, img: "logo/download (15).jpg" },
  { id: 23, name: "Street Fighter V", category: "Fighting", price: 19.99, original: 29.99, sale: true, rating: 4, img: "logo/Champion Edition Key Art - Street Fighter V Art Gallery.jpg" },
  { id: 24, name: "Tekken 7", category: "Fighting", price: 29.99, original: 39.99, sale: true, rating: 5, img: "logo/tekken 7.jpg" },
  { id: 25, name: "Mortal Kombat 11", category: "Fighting", price: 24.99, original: 39.99, sale: true, rating: 5, img: "logo/mortal 11 combat.jpg" },
  { id: 26, name: "Far Cry 6", category: "FPS", price: 39.99, original: 59.99, sale: false, rating: 4, img: "logo/far cry6.jpg" },
  { id: 27, name: "Rainbow Six Siege", category: "FPS", price: 14.99, original: 29.99, sale: true, rating: 4, img: "logo/Rainbow Six Siege Announces Compensation Following___.jpg" },
  { id: 28, name: "Apex Legends", category: "Battle Royale", price: 0, original: 0, sale: false, rating: 5, img: "logo/apex legends.jpg" },
  { id: 29, name: "PUBG", category: "Battle Royale", price: 19.99, original: 29.99, sale: true, rating: 4, img: "logo/pubg.jpg" },
  { id: 30, name: "Terraria", category: "Sandbox", price: 9.99, original: 19.99, sale: true, rating: 5, img: "logo/Vintage Game Tin Sign,Terraria Poster,Metal Poster for Wall Decor 8x12 inch.jpg" },
  { id: 31, name: "Stardew Valley", category: "Simulation", price: 14.99, original: 19.99, sale: true, rating: 5, img: "logo/star dew valley.jpg" },
  { id: 32, name: "The Sims 4", category: "Simulation", price: 29.99, original: 39.99, sale: true, rating: 4, img: "logo/The Sims 4.jpg" },
  { id: 33, name: "ARK: Survival Evolved", category: "Survival", price: 24.99, original: 49.99, sale: true, rating: 4, img: "logo/ARK Survival Evolved Extinction Game.jpg" },
  { id: 34, name: "Valheim", category: "Survival", price: 19.99, original: 29.99, sale: true, rating: 5, img: "logo/Valheim Check more at https___freedownloadskey_com_product_valheim_.jpg" },
  { id: 35, name: "Dark Souls III", category: "RPG", price: 24.99, original: 39.99, sale: true, rating: 5, img: "logo/Dark Souls III (2016).jpg" },
  { id: 36, name: "Bloodborne", category: "RPG", price: 19.99, original: 39.99, sale: true, rating: 5, img: "logo/blood brone.jpg" },
  { id: 37, name: "Hitman 3", category: "Stealth", price: 29.99, original: 59.99, sale: true, rating: 4, img: "logo/Hitman III (2021).jpg" },
  { id: 38, name: "Control", category: "Action", price: 24.99, original: 39.99, sale: true, rating: 4, img: "logo/Control PS4 Cover.jpg" },
  { id: 39, name: "Ghost of Tsushima", category: "Action", price: 39.99, original: 59.99, sale: false, rating: 5, img: "logo/Ghost of Tsushima.jpg" },
  { id: 40, name: "League of Legends: Wild Rift", category: "MOBA", price: 0, original: 0, sale: false, rating: 5, img: "logo/Mach bei League of Legends_ Wild Rift Esports-Turnieren mit _ Game_tv.jpg" },
  { id: 41, name: "Paladins", category: "FPS", price: 0, original: 0, sale: false, rating: 4, img: "logo/paladins.jpg" },
  { id: 42, name: "Smite", category: "MOBA", price: 0, original: 0, sale: false, rating: 4, img: "logo/Smite 2 Alpha Free Download For PC.jpg" },
  { id: 43, name: "Rocket League", category: "Sports", price: 19.99, original: 29.99, sale: true, rating: 5, img: "logo/Rocket League Wallpaper.jpg" },
  { id: 44, name: "Forza Horizon 5", category: "Racing", price: 49.99, original: 59.99, sale: false, rating: 5, img: "logo/Forza Horizon 5 Standard Edition.jpg" },
  { id: 45, name: "Gran Turismo 7", category: "Racing", price: 39.99, original: 59.99, sale: true, rating: 4, img: "logo/gran turismo.jpg" },
  { id: 46, name: "Need for Speed Heat", category: "Racing", price: 29.99, original: 49.99, sale: true, rating: 4, img: "logo/Acheter Need for Speed Heat - PC (EA App).jpg" },
  { id: 47, name: "The Last of Us Part II", category: "Action", price: 39.99, original: 59.99, sale: false, rating: 5, img: "logo/THE LAST OF US_ PART II (2020 VIDEO GAME) - ONE EYE SYMBOLISM.jpg" },
  { id: 48, name: "Sekiro: Shadows Die Twice", category: "Action", price: 29.99, original: 59.99, sale: true, rating: 5, img: "logo/seiko.jpg" },
  { id: 49, name: "Monster Hunter: World", category: "RPG", price: 34.99, original: 59.99, sale: true, rating: 4, img: "logo/monster hunter.jpg" },
  { id: 50, name: "Cuphead", category: "Platformer", price: 14.99, original: 19.99, sale: true, rating: 5, img: "logo/cuphead.jpg" }
];
